// src/components/add-player-form.tsx
import { useState, type FormEvent } from 'react';
import { useTranslation } from '@/hooks/use-locale';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

interface AddPlayerFormProps {
	onAdd: (name: string) => void;
}

export function AddPlayerForm({ onAdd }: AddPlayerFormProps) {
	const t = useTranslation();
	const [name, setName] = useState('');
	const trimmed = name.trim();

	function submit(event: FormEvent) {
		event.preventDefault();
		if (!trimmed) return;
		onAdd(trimmed);
		setName('');
	}

	return (
		<form onSubmit={submit} className="flex gap-2">
			<Input
				type="text"
				value={name}
				onChange={(event) => setName(event.target.value)}
				placeholder={t.addPlayerForm.playerNamePlaceholder}
				aria-label={t.addPlayerForm.playerNamePlaceholder}
			/>
			<Button type="submit" disabled={!trimmed}>
				{t.addPlayerForm.addPlayer}
			</Button>
		</form>
	);
}

// src/lib/AddPlayerForm.svelte
<script lang="ts">
	import { locale } from './locale.svelte';

	interface Props {
		onadd: (name: string) => void;
		label?: string;
	}

	let { onadd, label }: Props = $props();

	let effectiveLabel = $derived(label ?? locale.t.addPlayerForm.playerNamePlaceholder);

	let name = $state('');

	function submit(event: SubmitEvent) {
		event.preventDefault();
		if (!name.trim()) return;

		onadd(name.trim());
		name = '';
	}
</script>

<form class="flex space-x-4" onsubmit={submit}>
	<input
		type="text"
		bind:value={name}
		placeholder={effectiveLabel}
		aria-label={effectiveLabel}
		class="flex-1 rounded border border-[var(--table-border)] bg-[var(--card)] px-3 py-2"
	/>
	<button
		type="submit"
		class="rounded bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
		disabled={!name.trim()}
	>
		{locale.t.addPlayerForm.addPlayer}
	</button>
</form>
