// src/components/language-switcher.tsx
import { useLocale, useTranslation } from '@/hooks/use-locale';
import { localeStore } from '@/lib/locale-store';
import { LOCALES, LOCALE_LABELS, type Locale } from '@/lib/translations';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';

export function LanguageSwitcher() {
	const locale = useLocale();
	const t = useTranslation();

	return (
		<NativeSelect
			value={locale}
			onChange={(event) => localeStore.set(event.target.value as Locale)}
			aria-label={t.language.switchLabel}
		>
			{LOCALES.map((code) => (
				<NativeSelectOption key={code} value={code}>
					{LOCALE_LABELS[code]}
				</NativeSelectOption>
			))}
		</NativeSelect>
	);
}

// src/lib/LanguageSwitcher.svelte
<script lang="ts">
	import { locale } from './locale.svelte';
	import { LOCALES, LOCALE_LABELS, type Locale } from './translations';

	function onchange(event: Event) {
		locale.set((event.target as HTMLSelectElement).value as Locale);
	}
</script>

<select
	class="rounded-md border border-[var(--table-border)] bg-[var(--card)] px-3 py-2"
	aria-label={locale.t.language.switchLabel}
	value={locale.current}
	{onchange}
>
	{#each LOCALES as code (code)}
		<option value={code}>{LOCALE_LABELS[code]}</option>
	{/each}
</select>
