// src/components/scoreboard.tsx
import { useState } from 'react';

import { AddPlayerForm } from '@/components/add-player-form';
import { ConfirmDialog } from '@/components/confirm-dialog';
import { LanguageSwitcher } from '@/components/language-switcher';
import { PlayerChips } from '@/components/player-chips';
import { ScoreDialog, type ScoreDialogSelection } from '@/components/score-dialog';
import { ScoreTable } from '@/components/score-table';
import { ThemeToggle } from '@/components/theme-toggle';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { usePlayer, usePlayers } from '@/hooks/use-game';
import { useTranslation } from '@/hooks/use-locale';
import { gameStore } from '@/lib/game-store';
import type { ScoringCategory } from '@/lib/types';

export function Scoreboard() {
	const t = useTranslation();
	const players = usePlayers();
	const [selected, setSelected] = useState<ScoreDialogSelection | null>(null);
	const selectedPlayer = usePlayer(selected?.playerId ?? null);
	const current = selected && selectedPlayer ? selectedPlayer.scores[selected.category] : null;

	function openCell(category: ScoringCategory, playerId: string) {
		setSelected({ category, playerId });
	}

	function closeDialog() {
		setSelected(null);
	}

	function applyScore(score: number) {
		if (selected) gameStore.scoreCategory(selected.category, score, selected.playerId);
		closeDialog();
	}

	function eraseScore() {
		if (selected) gameStore.clearCategory(selected.category, selected.playerId);
		closeDialog();
	}

	return (
		<div className="min-h-dvh bg-background text-foreground">
			<div className="mx-auto w-full max-w-6xl px-4 py-6 sm:px-6 sm:py-10">
				<header className="mb-6 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
					<div>
						<h1 className="text-3xl font-extrabold">{t.scoreboard.title}</h1>
						<p className="mt-1 text-sm text-muted-foreground">{t.scoreboard.subtitle}</p>
					</div>
					<div className="flex items-center gap-2">
						<LanguageSwitcher />
						<ThemeToggle />
						<ConfirmDialog
							trigger={<Button variant="destructive">{t.scoreboard.reset}</Button>}
							title={t.scoreboard.confirmResetTitle}
							description={t.scoreboard.confirmResetBody}
							confirmLabel={t.scoreboard.confirmResetConfirm}
							cancelLabel={t.common.cancel}
							onConfirm={() => gameStore.reset()}
						/>
					</div>
				</header>

				{players.length === 0 ? (
					<Card>
						<CardHeader>
							<CardTitle>{t.scoreboard.addPlayers}</CardTitle>
						</CardHeader>
						<CardContent>
							<AddPlayerForm onAdd={(name) => gameStore.addPlayer(name)} />
						</CardContent>
					</Card>
				) : (
					<div className="space-y-6">
						<Card>
							<CardContent className="space-y-4">
								<PlayerChips players={players} />
								<Separator />
								<div>
									<h2 className="mb-2 text-lg font-semibold">{t.scoreboard.addMorePlayers}</h2>
									<AddPlayerForm onAdd={(name) => gameStore.addPlayer(name)} />
								</div>
							</CardContent>
						</Card>

						<ScoreTable players={players} onOpenCell={openCell} />
					</div>
				)}
			</div>

			<ScoreDialog
				selected={selected}
				current={current}
				onScore={applyScore}
				onErase={eraseScore}
				onClose={closeDialog}
			/>
		</div>
	);
}

// src/lib/Scoreboard.svelte
<script lang="ts">
	import AddPlayerForm from './AddPlayerForm.svelte';
	import LanguageSwitcher from './LanguageSwitcher.svelte';
	import ScoreModal from './ScoreModal.svelte';
	import { game } from './gameStore.svelte';
	import { locale } from './locale.svelte';
	import { theme } from './theme.svelte';
	import type { Player, ScoringCategory } from './types';
	import { LOWER_CATEGORIES, UPPER_CATEGORIES } from './types';
	import { UPPER_BONUS_THRESHOLD, grandTotal, lowerTotal, upperBonus, upperTotal } from './scoring';

	let t = $derived(locale.t);

	let selectedCategory = $state<ScoringCategory | null>(null);
	let selectedPlayerId = $state<string | null>(null);

	let selectedPlayer = $derived(
		game.players.find((player) => player.id === selectedPlayerId) ?? null
	);

	function openScoreModal(category: ScoringCategory, playerId: string) {
		selectedCategory = category;
		selectedPlayerId = playerId;
	}

	function closeScoreModal() {
		selectedCategory = null;
		selectedPlayerId = null;
	}

	function applyScore(score: number) {
		if (selectedCategory && selectedPlayerId) {
			game.scoreCategory(selectedCategory, score, selectedPlayerId);
		}
		closeScoreModal();
	}

	function eraseScore() {
		if (selectedCategory && selectedPlayerId) {
			game.clearCategory(selectedCategory, selectedPlayerId);
		}
		closeScoreModal();
	}
</script>

{#snippet categoryRow(category: ScoringCategory)}
	<tr class="border-b border-[var(--table-border-soft)]">
		<td
			class="border-r border-[var(--table-border)] bg-[var(--row-header)] px-4 py-3 font-semibold"
		>
			{t.categories[category]}
		</td>
		{#each game.players as player (player.id)}
			<td
				class="border-r border-[var(--table-border)] bg-[var(--card)] p-0 text-center last:border-r-0"
			>
				<button
					class="min-h-[48px] w-full cursor-pointer px-4 py-3 transition-colors duration-200 hover:bg-[var(--hover)]"
					aria-label={t.scoreboard.scoreFor(t.categories[category], player.name)}
					onclick={() => openScoreModal(category, player.id)}
				>
					{#if player.scores[category] !== null}
						<span class="text-foreground font-medium">{player.scores[category]}</span>
					{:else}
						<span class="text-sm font-medium" style="color: var(--accent);"
							>{t.scoreboard.clickToScore}</span
						>
					{/if}
				</button>
			</td>
		{/each}
	</tr>
{/snippet}

{#snippet totalRow(label: string, value: (player: Player) => number)}
	<tr class="border border-[var(--table-border)]">
		<td class="px-4 py-3 font-bold">{label}</td>
		{#each game.players as player (player.id)}
			<td class="border border-[var(--table-border)] px-4 py-3 text-center font-bold">
				{value(player)}
			</td>
		{/each}
	</tr>
{/snippet}

<div class="min-h-screen p-6">
	<div class="mx-auto max-w-6xl">
		<header
			class="mb-6 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"
		>
			<div>
				<h1 class="text-3xl font-extrabold">{t.scoreboard.title}</h1>
				<p class="text-muted mt-1 text-sm">
					{t.scoreboard.subtitle}
				</p>
			</div>
			<div class="flex items-center space-x-3">
				<LanguageSwitcher />
				<button
					class="btn-primary rounded-md border border-transparent px-4 py-2"
					onclick={() => theme.toggle()}
					aria-pressed={theme.isDark}
				>
					{theme.isDark ? t.scoreboard.lightMode : t.scoreboard.darkMode}
				</button>
				<button
					class="rounded-md bg-red-600 px-4 py-2 text-white hover:bg-red-700"
					onclick={() => game.reset()}
				>
					{t.scoreboard.reset}
				</button>
			</div>
		</header>

		{#if game.players.length === 0}
			<div class="card mb-6 p-6">
				<h2 class="mb-4 text-xl font-semibold">{t.scoreboard.addPlayers}</h2>
				<AddPlayerForm onadd={(name) => game.addPlayer(name)} />
			</div>
		{:else}
			<div class="card mb-6 p-6">
				<div class="mb-4 flex flex-wrap items-center justify-between gap-2">
					<h2 class="text-xl font-semibold">{t.scoreboard.title}</h2>
					<div class="flex flex-wrap gap-2">
						{#each game.players as player (player.id)}
							<div
								class="flex items-center space-x-2 rounded bg-blue-500/15 px-3 py-1 text-blue-500"
							>
								<span class="font-medium">{player.name}</span>
								<button
									class="ml-2 text-xs text-red-500 hover:text-red-400"
									aria-label={t.scoreboard.removePlayer(player.name)}
									onclick={() => game.removePlayer(player.id)}
								>
									×
								</button>
							</div>
						{/each}
					</div>
				</div>

				<div class="border-t border-[var(--table-border)] pt-4">
					<h3 class="mb-2 text-lg font-semibold">{t.scoreboard.addMorePlayers}</h3>
					<AddPlayerForm onadd={(name) => game.addPlayer(name)} />
				</div>
			</div>

			<div class="overflow-x-auto rounded-lg">
				<table class="w-full border-collapse">
					<thead class="bg-transparent">
						<tr>
							<th class="border-r border-[var(--table-border)] px-4 py-3 text-left font-semibold">
								{t.scoreboard.categoryHeader}
							</th>
							{#each game.players as player (player.id)}
								<th
									class="border-r border-[var(--table-border)] px-4 py-3 text-center font-semibold"
								>
									{player.name}
								</th>
							{/each}
						</tr>
					</thead>
					<tbody>
						{#each UPPER_CATEGORIES as category (category)}
							{@render categoryRow(category)}
						{/each}

						{@render totalRow(t.scoreboard.upperTotal, upperTotal)}

						<tr
							class="border border-b-4 border-[var(--table-border-soft)]"
							style="border-bottom-color: var(--accent);"
						>
							<td class="px-4 py-3 font-semibold">{t.scoreboard.bonus(UPPER_BONUS_THRESHOLD)}</td>
							{#each game.players as player (player.id)}
								<td class="border border-[var(--table-border)] px-4 py-3 text-center">
									{#if upperBonus(player) > 0}
										<span class="font-bold text-green-500">{upperBonus(player)}</span>
									{:else}
										<span class="text-muted">0</span>
									{/if}
								</td>
							{/each}
						</tr>

						{#each LOWER_CATEGORIES as category (category)}
							{@render categoryRow(category)}
						{/each}

						{@render totalRow(t.scoreboard.lowerTotal, lowerTotal)}

						<tr
							class="border border-t-4 border-[var(--table-border)]"
							style="border-top-color: var(--accent);"
						>
							<td class="px-4 py-3 text-lg font-bold">{t.scoreboard.grandTotal}</td>
							{#each game.players as player (player.id)}
								<td
									class="border border-[var(--table-border)] px-4 py-3 text-center text-lg font-bold"
								>
									{grandTotal(player)}
								</td>
							{/each}
						</tr>
					</tbody>
				</table>
			</div>
		{/if}
	</div>
</div>

{#if selectedCategory}
	<ScoreModal
		category={selectedCategory}
		current={selectedPlayer?.scores[selectedCategory] ?? null}
		onscore={applyScore}
		onerase={eraseScore}
		onclose={closeScoreModal}
	/>
{/if}
